name: Daily Automated Tests
on:
  schedule:
    # Run at 2 AM UTC (adjust this time as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      CORPORATE_EMAIL: ${{ secrets.CORPORATE_EMAIL }}
      CORPORATE_PASSWORD: ${{ secrets.CORPORATE_PASSWORD }}
      SAGE_EMAIL: ${{ secrets.SAGE_EMAIL }}
      SAGE_PASSWORD: ${{ secrets.SAGE_PASSWORD }}
      PROFESSOR_EMAIL: ${{ secrets.PROFESSOR_EMAIL }}
      PROFESSOR_PASSWORD: ${{ secrets.PROFESSOR_PASSWORD }}
      STUDENT_EMAIL: ${{ secrets.STUDENT_EMAIL }}
      STUDENT_PASSWORD: ${{ secrets.STUDENT_PASSWORD }}
      MEMBER_EMAIL: ${{ secrets.MEMBER_EMAIL }}
      MEMBER_PASSWORD: ${{ secrets.MEMBER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        run: |
          DEBUG=pw:api npx playwright test
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
          
      # Add these steps to publish to GitHub Pages
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4
        
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'playwright-report'
          
      - name: Deploy to GitHub Pages
        id: deployment
        if: always()
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}